[workspace]
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "contracts/tokenomics/generator",
    "contracts/tokenomics/maker",
    "contracts/tokenomics/staking",
    "contracts/tokenomics/vesting",
    "contracts/tokenomics/xastro_token",
    "contracts/pair_astro_xastro",
    "contracts/periphery/oracle",
]

[patch."https://github.com/astroport-fi/hidden_astroport_governance.git"]
astroport-governance = { git="https://github.com/astroport-fi/astroport-governance", branch="release" }

[patch."https://github.com/astroport-fi/astroport-core.git"]
astroport = { path = './packages/astroport' }
astroport-generator = { path = './contracts/tokenomics/generator' }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
